sudo: false
cache: bundler
bundler_args: --no-deployment
language: ruby
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - rbx2
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
